# Generated by Django 2.0.5 on 2018-05-05 14:57

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarticle', '0002_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
    ]
