# Generated by Django 2.0.5 on 2018-05-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarticle', '0003_auto_20180505_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
