# Generated by Django 2.0.5 on 2018-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarticle', '0004_auto_20180515_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='课程标签'),
        ),
    ]
