# Generated by Django 2.0.5 on 2018-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarticle', '0006_auto_20180522_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='文章标签'),
        ),
    ]
