# Generated by Django 2.0.5 on 2018-06-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180626_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本'),
        ),
    ]
