# Generated by Django 2.0.5 on 2018-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='昵称'),
        ),
    ]
